excluded:
    - Pods
  
disabled_rules:
    - trailing_whitespace
    
cyclomatic_complexity:
    ignores_case_statements: true
  
identifier_name:
    excluded: # excluded via string array
        - id
        - URL
        - url
        - app
    
function_body_length:
    warning: 80
    error: 120

file_length:
    warning: 500
    error: 800
  
type_body_length:
    warning: 500
    error: 700
